pageInfo:
  title: CLAPStack
  description: ''
  navLinks:
    - title: GitHub
      path: https://github.com/
      target: newtab
    - title: Documentation
      path: https://dashy.to/docs
      target: newtab
appConfig:
  theme: dracula
  layout: auto
  iconSize: medium
sections:
  - name: Links
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: VScode
        url: http://localhost:18443
        target: newtab
        id: 0_513_vscode
      - title: Dozzle
        url: http://localhost:19999
        target: newtab
        id: 1_513_dozzle
      - title: DBGate
        description: DBGate
        url: http://localhost:13000
        target: newtab
        id: 2_513_dbgate
      - title: Portainer
        description: Portainer
        url: https://localhost:9443
        target: newtab
        id: 3_513_portainer
  - name: Airflow
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Web Console
        description: Airflow web console
        url: http://localhost:18080
        target: newtab
        id: 0_724_webconsole
